apiVersion: v1
kind: Service
metadata:
  name: stockora-client
  namespace: stockora
  labels:
    app.kubernetes.io/name: stockora-client
    app.kubernetes.io/part-of: stockora-enterprise
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: stockora-client
