apiVersion: v1
kind: Namespace
metadata:
  name: stockora
  labels:
    app.kubernetes.io/name: stockora-enterprise
    app.kubernetes.io/part-of: stockora-enterprise
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
