apiVersion: v1
kind: ServiceAccount
metadata:
  name: stockora-server-sa
  namespace: stockora
  labels:
    app.kubernetes.io/name: stockora-server
    app.kubernetes.io/part-of: stockora-enterprise
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stockora-client-sa
  namespace: stockora
  labels:
    app.kubernetes.io/name: stockora-client
    app.kubernetes.io/part-of: stockora-enterprise
automountServiceAccountToken: false
