apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stockora-staging

resources:
  - ../../base

namePrefix: staging-

patches:
  - target:
      kind: Deployment
      name: stockora-server
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: stockora-client
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: stockora-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.stockora.enterprise
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.stockora.enterprise
